version: 3.0.0
logo: /images/avatar.png
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/bellakongqn/bella-blog'
footer:
    links: {}
article:
    highlight: atom-one-light
    thumbnail: true
    readtime: true
search:
    type: insight
comment:
    type: 
share:
    type: 
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        type: profile
        position: left
        author: bella
        author_title: 兔子与小狗
        location: 大连
        avatar: /img/avatar.png
        gravatar: /img/avatar.png
        avatar_rounded: false
        follow_link: 'https://github.com/bellakongqn'
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/bellakongqn'
    -
        type: toc
        position: left
    -
        type: links
        position: left
        links:
            Hexo: 'https://hexo.io'
            PPOffice: 'https://github.com/bellakongqn'
    -
        type: categories
        position: left
    -
        type: tagcloud
        position: left
    -
        type: recent_posts
        position: right
    -
        type: archives
        position: right
    -
        type: tags
        position: right
plugins:
    animejs: true
    gallery: true
    mathjax: true
    hotjar:
        site_id: 
    progressbar: true
    clipboard: true
    busuanzi: false
    outdated_browser: true
    back_to_top: true
    google_analytics:
        tracking_id: 
    baidu_analytics:
        tracking_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
head:
    favicon: /images/avatar.png
    canonical_url: 
    open_graph:
        fb_app_id: 
        fb_admins: 
        twitter_id: 
        twitter_site: 
        google_plus: 
    meta: 
    rss: 
